# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    io.damelyngdoh.multidatasourcespringapp: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  # datasource:
  #   type: com.zaxxer.hikari.HikariDataSource
  #   url: jdbc:postgresql://localhost:5432/alphadb
  #   username: postgres
  #   password: consortium
  #   hikari:
  #     poolName: Hikari
  #     auto-commit: false
  # jpa:
  #   database-platform: io.github.jhipster.domain.util.FixedPostgreSQL10Dialect
  #   show-sql: true
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
  sleuth:
    sampler:
      probability: 1 # report 100% of traces
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true

server:
  port: 6050

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  # CORS is disabled by default on microservices, as you should access them through a gateway.
  # If you want to enable it, please uncomment the configuration below.
  # cors:
  #     allowed-origins: "*"
  #     allowed-methods: "*"
  #     allowed-headers: "*"
  #     exposed-headers: "Authorization,Link,X-Total-Count"
  #     allow-credentials: true
  #     max-age: 1800
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:6050
  metrics:
    logs: # Reports metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  audit-events:
    retention-period: 30 # Number of days before audit events are deleted.

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:

persistence-config:
  common-jpa:
    open-in-view: false
    database-platform: io.github.jhipster.domain.util.FixedPostgreSQL10Dialect
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.connection.autocommit: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  
  common-datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: <username>
    password: <password>
    hikari:
      poolName: Hikari
      auto-commit: false
  
  alpha:
    jpa:
      open-in-view: ${persistence-config.common-jpa.open-in-view}
      database-platform: ${persistence-config.common-jpa.database-platform}
      show-sql: ${persistence-config.common-jpa.show-sql}
      properties:
        hibernate.jdbc.time_zone: ${persistence-config.common-jpa.properties.hibernate.jdbc.time_zone}
        hibernate.id.new_generator_mappings: ${persistence-config.common-jpa.properties.hibernate.id.new_generator_mappings}
        hibernate.connection.provider_disables_autocommit: ${persistence-config.common-jpa.properties.hibernate.connection.provider_disables_autocommit}
        hibernate.connection.autocommit: ${persistence-config.common-jpa.properties.hibernate.connection.autocommit}
        hibernate.cache.use_second_level_cache: ${persistence-config.common-jpa.properties.hibernate.cache.use_second_level_cache}
        hibernate.cache.use_query_cache: ${persistence-config.common-jpa.properties.hibernate.cache.use_query_cache}
        hibernate.generate_statistics: ${persistence-config.common-jpa.properties.hibernate.generate_statistics}
        # modify batch size as necessary
        hibernate.jdbc.batch_size: ${persistence-config.common-jpa.properties.hibernate.jdbc.batch_size}
        hibernate.order_inserts: ${persistence-config.common-jpa.properties.hibernate.order_inserts}
        hibernate.order_updates: ${persistence-config.common-jpa.properties.hibernate.order_updates}
        hibernate.query.fail_on_pagination_over_collection_fetch: ${persistence-config.common-jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch}
        hibernate.query.in_clause_parameter_padding: ${persistence-config.common-jpa.properties.hibernate.query.in_clause_parameter_padding}
        hibernate.default_schema: alpha_schema
      hibernate:
        ddl-auto: ${persistence-config.common-jpa.hibernate.ddl-auto}
        naming:
          physical-strategy: ${persistence-config.common-jpa.hibernate.naming.physical-strategy}
          implicit-strategy: ${persistence-config.common-jpa.hibernate.naming.implicit-strategy}
    datasource:
      type: ${persistence-config.common-datasource.type}
      url: jdbc:postgresql://localhost:5432/alphadb
      username: ${persistence-config.common-datasource.username}
      password: ${persistence-config.common-datasource.password}
      hikari:
        poolName: ${persistence-config.common-datasource.hikari.poolName}
        auto-commit: ${persistence-config.common-datasource.hikari.auto-commit}

  beta:
    jpa:
      open-in-view: ${persistence-config.common-jpa.open-in-view}
      database-platform: ${persistence-config.common-jpa.database-platform}
      show-sql: ${persistence-config.common-jpa.show-sql}
      properties:
        hibernate.jdbc.time_zone: ${persistence-config.common-jpa.properties.hibernate.jdbc.time_zone}
        hibernate.id.new_generator_mappings: ${persistence-config.common-jpa.properties.hibernate.id.new_generator_mappings}
        hibernate.connection.provider_disables_autocommit: ${persistence-config.common-jpa.properties.hibernate.connection.provider_disables_autocommit}
        hibernate.connection.autocommit: ${persistence-config.common-jpa.properties.hibernate.connection.autocommit}
        hibernate.cache.use_second_level_cache: ${persistence-config.common-jpa.properties.hibernate.cache.use_second_level_cache}
        hibernate.cache.use_query_cache: ${persistence-config.common-jpa.properties.hibernate.cache.use_query_cache}
        hibernate.generate_statistics: ${persistence-config.common-jpa.properties.hibernate.generate_statistics}
        # modify batch size as necessary
        hibernate.jdbc.batch_size: ${persistence-config.common-jpa.properties.hibernate.jdbc.batch_size}
        hibernate.order_inserts: ${persistence-config.common-jpa.properties.hibernate.order_inserts}
        hibernate.order_updates: ${persistence-config.common-jpa.properties.hibernate.order_updates}
        hibernate.query.fail_on_pagination_over_collection_fetch: ${persistence-config.common-jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch}
        hibernate.query.in_clause_parameter_padding: ${persistence-config.common-jpa.properties.hibernate.query.in_clause_parameter_padding}
        hibernate.default_schema: beta_schema
      hibernate:
        ddl-auto: ${persistence-config.common-jpa.hibernate.ddl-auto}
        naming:
          physical-strategy: ${persistence-config.common-jpa.hibernate.naming.physical-strategy}
          implicit-strategy: ${persistence-config.common-jpa.hibernate.naming.implicit-strategy}
    datasource:
      type: ${persistence-config.common-datasource.type}
      url: jdbc:postgresql://localhost:5432/betadb
      username: ${persistence-config.common-datasource.username}
      password: ${persistence-config.common-datasource.password}
      hikari:
        poolName: ${persistence-config.common-datasource.hikari.poolName}
        auto-commit: ${persistence-config.common-datasource.hikari.auto-commit}